services:
  mysql:
    image: mysql:8.0
    container_name: image_detection_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: image_detection
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./front
    container_name: image_detection_front
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
    volumes:
      - ./front:/app
    command: ["npm", "run", "start"]

  backend:
    build:
      context: ./back
    container_name: image_detection_back
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=image_detection
    volumes:
      - ./back:/app
