version: "3.9"

services:
  mysql:
    build:
      context: ./db
    container_name: image_detection_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: image_detection
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./back
    container_name: image_detection_back
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user 
      DB_PASSWORD: app_password
      DB_NAME: image_detection
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./front
    container_name: image_detection_front
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./front:/app
    working_dir: /app
    command: ["npm", "run", "start"]