name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  database:
    uses: ./.github/workflows/database.yml
    with:
      db_name: image_detection

  back:
    needs: database
    uses: ./.github/workflows/back.yml

  front:
    needs: back
    uses: ./.github/workflows/front.yml

  deploy-to-coolify:
    needs: [front, back, database]
    uses: ./.github/workflows/deploy-to-coolify.yml