name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  database:
    uses: ./.github/workflows/jobs/database.yml
    with:
      db_name: image_detection

  front:
    needs: database
    uses: ./.github/workflows/jobs/front.yml

  back:
    needs: front
    uses: ./.github/workflows/jobs/back.yml

  deploy-to-coolify:
    needs: back
    if: ${{ needs.back.result == 'success' }}
    uses: ./.github/workflows/deploy-to-coolify.yml
