name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  database:
    uses: ./.github/workflows/jobs/database.yml
    with:
      db_name: image_detection
  front:
    uses: ./.github/workflows/jobs/front.yml